import AuthGuard from "../Components/Authguard";
import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "./Context/userContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider>
        <AuthGuard>
          {children}
        </AuthGuard>
        </UserProvider>
      </body>
    </html>
  );
}