export const ASSET_CONFIGS = {

  empAsset: {
    apiEndpoint: "/api/emp-assets",
    title: "Employee Asset",
    fields: [
      { key: "Asset Type",            label: "Asset Type",            type: "text" },
      { key: "Status",                label: "Status",                type: "select", options: ["Active", "Inactive"] },
      { key: "Employees Id",          label: "Employee ID",           type: "text" },
      { key: "Username",              label: "Username",              type: "text" },
      { key: "Current Asset TAG",     label: "Current Asset TAG",     type: "text" },
      { key: "Make",                  label: "Make",                  type: "text" },
      { key: "Model",                 label: "Model",                 type: "text" },
      { key: "Serial Number",         label: "Serial Number",         type: "text" },
      { key: "RAM",                   label: "RAM",                   type: "text" },
      { key: "Processor",             label: "Processor",             type: "text" },
      { key: "HDD/SSD",               label: "HDD/SSD",               type: "text" },
      { key: "Designation",           label: "Designation",           type: "text" },
      { key: "Date of Joining",       label: "Date of Joining",       type: "text" },
      { key: "Primary Asset Tag no",  label: "Primary Asset Tag No",  type: "text" },
      { key: "Remark",                label: "Remark",                type: "text" },
      { key: "Asset location",        label: "Asset Location",        type: "text" },
      { key: "Old Asset TAG",         label: "Old Asset TAG",         type: "text" },
      { key: "Additional Accessories",label: "Additional Accessories",type: "text" },
      { key: "Dept",                  label: "Department",            type: "text" },
      { key: "Common Asset",          label: "Common Asset",          type: "text" },
      { key: "Additional Remarks",    label: "Additional Remarks",    type: "text" },
    ],
  },

  instock: {
    apiEndpoint: "/api/instock-assets",
    title: "Instock Asset",
    fields: [
      { key: "Asset Type",    label: "Asset Type",    type: "text" },
      { key: "Scrap",         label: "Scrap",         type: "select", options: ["Yes", "No"] },
      { key: "Username",      label: "Username",      type: "text" },
      { key: "Asset Tag No",  label: "Asset Tag No",  type: "text" },
      { key: "Make",          label: "Make",          type: "text" },
      { key: "Model",         label: "Model",         type: "text" },
      { key: "Serial Number", label: "Serial Number", type: "text" },
      { key: "RAM",           label: "RAM",           type: "text" },
      { key: "Processor",     label: "Processor",     type: "text" },
      { key: "HDD/SSD",       label: "HDD/SSD",       type: "text" },
      { key: "Remarks",       label: "Remarks",       type: "text" },
      { key: "Repair Status", label: "Repair Status", type: "text" },
    ],
  },

  purchase: {
    apiEndpoint: "/api/asset-purchases",
    title: "Asset Purchase",
    fields: [
      { key: "invoiceNo",            label: "Invoice No",       type: "text" },
      { key: "category",             label: "Category",         type: "text" },
      { key: "assetCode",            label: "Asset Code",       type: "text" },
      { key: "assetTag",             label: "Asset Tag",        type: "text" },
      { key: "assignedTo",           label: "Assigned To",      type: "text" },
      { key: "brand",                label: "Brand",            type: "text" },
      { key: "model",                label: "Model",            type: "text" },
      { key: "serialNumber",         label: "Serial Number",    type: "text" },
      { key: "specs.ram",            label: "RAM",              type: "text" },
      { key: "specs.cpu",            label: "CPU",              type: "text" },
      { key: "specs.storage",        label: "Storage",          type: "text" },
      { key: "purchaseDate",         label: "Purchase Date",    type: "date" },
      { key: "department",           label: "Department",       type: "text" },
      { key: "vendorName",           label: "Vendor Name",      type: "text" },
      { key: "warranty.startDate",   label: "Warranty Start",   type: "date" },
      { key: "warranty.endDate",     label: "Warranty End",     type: "date" },
      { key: "remarks",              label: "Remarks",          type: "text" },
    ],
  },

  retail: {
    apiEndpoint: "/api/assets",
    title: "Retail Asset",
    fields: [
      { key: "type",              label: "Asset Type",    type: "text" },
      { key: "assetTag",          label: "Asset Tag",     type: "text" },
      { key: "brand",             label: "Brand",         type: "text" },
      { key: "model",             label: "Model",         type: "text" },
      { key: "serialNumber",      label: "Serial Number", type: "text" },
      { key: "specs.ram",         label: "RAM",           type: "text" },
      { key: "specs.cpu",         label: "CPU",           type: "text" },
      { key: "specs.storage",     label: "Storage",       type: "text" },
      { key: "location.name",     label: "Location",      type: "text" },
      { key: "remarks",           label: "Remarks",       type: "text" },
    ],
  },

};